; runonce.g
; called after config.g. When it has been executed, it is automatically deleted!
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+6 on Sat Mar 18 2023 10:37:44 GMT+0100 (Central European Standard Time)
M552 S0                                    ; disable network
G4 S5                                      ; wait half a second
M587 S"VodafoneSbaioccone" P"gelatone1309" ; configure WiFi
G4 S5
M552 S1                                    ; enable network
