; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+6 on Sat Mar 18 2023 10:37:45 GMT+0100 (Central European Standard Time)

