; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+6 on Sat Mar 18 2023 10:37:45 GMT+0100 (Central European Standard Time)
; Wait for set temperatures to be reached
M116 P0

